DEFINE VARIABLE qh AS HANDLE     NO-UNDO.
DEFINE VARIABLE wlok AS LOGICAL    NO-UNDO.

 DO STOP-AFTER 1 :
 

CREATE QUERY qh.
qh:SET-BUFFERS(BUFFER doc:HANDLE).
ETIME(TRUE).
wlok = qh:QUERY-PREPARE( "PRESELECT EACH doc NO-LOCK " ) .
qh:QUERY-OPEN . 

 END.

DISP ETIME wlok  qh:NUM-RESULTS.
 
IF VALID-HANDLE(qh) THEN DELETE OBJECT qh.
