/* iconv_UTF-8_ISO8859-1.p */
DEFINE STREAM lsIN.
DEFINE STREAM lsOUT.
DEFINE VARIABLE lc_filename   AS CHARACTER NO-UNDO.
DEFINE VARIABLE jLigne        AS CHARACTER NO-UNDO.
lc_filename = "H:\tmp\AdrCliWsCreateRequest.xml".

INPUT STREAM lsIN FROM VALUE(lc_filename)   CONVERT TARGET "iso8859-1" SOURCE "utf-8".
OUTPUT STREAM lsOUT TO VALUE("H:\tmp\AdrCliWsCreateRequest2.xml").

REPEAT:
  IMPORT STREAM lsIN UNFORMATTED jLigne.
  PUT STREAM lsOUT UNFORMATTED jLigne SKIP.
END.
INPUT  STREAM lsIN  CLOSE.
OUTPUT STREAM lsOUT CLOSE.
